/**
 * =============================================================
 *  VECTOR WORKFLOW ENGINE
 * =============================================================
 *  This module executes multi-step plans generated by the LLM.
 *  It provides:
 *
 *   • Step validation
 *   • Plan validation
 *   • LLM-powered plan rewriting (autofix)
 *   • Dependency detection
 *   • DAG construction + cycle detection
 *   • Topological sorting
 *   • Parallel execution engine
 *   • Sequential fallback engine
 *
 *  The workflow engine is responsible for turning a high-level
 *  plan into deterministic, safe, and optimized execution.
 *
 *  This file is intentionally large — it contains the entire
 *  execution pipeline. Comments are structured by subsystem.
 * =============================================================
 */

// ------------------------------------------------------
//  BLOCK 1 — Types, Imports, OpenAI Client, Core Helpers
// ------------------------------------------------------

/**
 * ------------------------------------------------------
 *  TYPE DEFINITIONS
 * ------------------------------------------------------
 *  These interfaces define the structure of plans and
 *  steps used throughout the workflow engine.
 *
 *  PlanStep:
 *    A single executable action (e.g., read file, write file,
 *    search the web, update memory).
 *
 *  Plan:
 *    An ordered list of PlanStep objects. This is the main
 *    structure passed into executePlan().
 *
 *  StepValidationResult / PlanValidationResult:
 *    Used by the validation subsystem to ensure correctness
 *    before execution.
 *
 *  DAG:
 *    Directed Acyclic Graph used for dependency resolution
 *    and parallel execution.
 */

// -------------------------------------------------------------
//  PLAN + STEP TYPE DEFINITIONS
// -------------------------------------------------------------
//  These interfaces define the structure of executable plans
//  and their steps. They are used throughout the workflow engine
//  for validation, optimization, and execution.
// -------------------------------------------------------------

export interface PlanStep {
  number: number;           // Step number (1-based, stable across rewrites)
  tool: string;             // Tool name (must exist in toolRegistry)
  description?: string;   // Optional readable description of the step's purpose

  // Tool-specific fields (only some apply depending on the tool)
  filename?: string;
  content?: string;
  mode?: string;
  query?: string;
  key?: string;
  value?: string;

  // Execution behavior modifiers
  retry?: number;           // Number of retry attempts allowed
  autofix?: boolean;        // Whether LLM autofix is allowed for this step
  parallelGroup?: number;   // Assigned parallel execution group
}

export interface Plan {
  goal?: string;       // High-level goal (optional metadata)
  optimize?: boolean;  // Whether to run optimization pipeline
  parallel?: boolean;  // Whether to enable parallel execution
  autofix?: boolean;   // Whether autofix is enabled for the plan
  steps: PlanStep[];   // Ordered list of steps
}

export interface StepValidationResult {
  valid: boolean;
  error?: string;       // Error message if validation fails
}

export interface PlanValidationResult {
  valid: boolean;
  errors: string[];   // List of validation errors
}

export interface StepExecutionResult {
  step: number | null;          // Step number executed
  description?: string | null;  // Step description
  tool: string | null;          // Tool used
  parallelGroup?: number | null;

  startTime: number | null;
  endTime: number | null;
  durationMs: number | null;

  output: unknown;         // Tool output
  error: unknown;          // Error details if execution failed

  autofixAttempted: boolean;    // Whether autofix was triggered
  fixedStep?: PlanStep | null;  // Step after autofix (if applicable)
}

export interface DAG {
  adjacencyList: Map<number, number[]>;         // Forward edges 
  reverseAdjacencyList: Map<number, number[]>;  // Reverse edges
  inDegree: Map<number, number>;                // Node dependency counts
}

// -----------------------------
// IMPORTS
// -----------------------------

import dotenv from "dotenv";
import OpenAI from "openai";

import { fileWriterTool } from "./fileWriterTool";
import { fileReaderTool } from "./fileReaderTool";
import { fileUpdaterTool } from "./fileUpdaterTool";
import { webSearchTool } from "./webSearchTool";
import { saveMemory } from "./memoryTool";
import { vectorSystemPrompt } from "../vector";
import { skipTool } from "./skipTool";
import { toolRegistry } from "./toolRegistry";

dotenv.config();

// ------------------------------------------------------
//  OPENAI CLIENT
// ------------------------------------------------------
//  Used for:
//    • LLM-powered plan rewriting (autofix)
//    • LLM-powered optimization
//    • System-level reasoning

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY
});

// ------------------------------------------------------
//  CORE EXECUTION HELPERS (declared later in file)
// ------------------------------------------------------
//  These functions are implemented in later blocks but
//  referenced throughout the engine:
//
//    • executeSingleStep()
//    • validateStep()
//    • validatePlan()
//    • rewritePlan()
//    • buildDAG()
//    • topologicalSort()
//    • computeParallelLayers()
//    • detectCycle()
//    • extractCycle()
//    • deterministicOptimizeSteps()
//    • removeNoOpSteps()
//    • detectDependencies()
//    • optimizePlan()
//    • executeParallelGroups()
//    • executePlan()
// 

// =============================================================
//  BLOCK 2 — VALIDATION + AUTOFIX SUBSYSTEM
// =============================================================
//  This subsystem ensures that each step in a plan is valid,
//  well‑formed, and executable. If a step fails validation or
//  execution, the LLM attempts to automatically rewrite it.
//
//  Responsibilities:
//    • Step-level validation
//    • Plan-level validation
//    • LLM-powered step rewriting (autofix)
//    • Retry logic for corrected steps
//    • Ensuring required fields exist for each tool
//
//  This subsystem is the first line of defense against malformed
//  plans and is essential for safe autonomous execution.
// =============================================================


/**
 * -------------------------------------------------------------
 *  executeSingleStep()
 * -------------------------------------------------------------
 *  Executes a single plan step using the tool registry.
 *
 *  Responsibilities:
 *    • Validate required fields for the selected tool
 *    • Call the tool handler with the correct arguments
 *    • Return the tool output or throw on missing fields
 *
 *  Used by:
 *    • Normal execution
 *    • Retry logic
 *    • Autofix execution attempts
 */
async function executeSingleStep(step: PlanStep): Promise<unknown> {
  const entry = toolRegistry[step.tool];

  if (!entry) {
    return { success: false, error: `Unknown tool: ${step.tool}` };
  }

  // Validate required fields
  for (const field of entry.requiredFields || []) {
    if ((step as any)[field] === undefined) {
      throw new Error(`Missing required field "${field}" for tool "${step.tool}"`);
    }
  }

  // Execute the tool
  return await entry.handler(
    step.filename,
    step.content,
    step.mode,
    step.query,
    step.key,
    step.value,
    step.description
  );
}

// -------------------------------------------------------------
//  RETRY LOGIC
// -------------------------------------------------------------
/**
 * Simple wrapper around executeSingleStep().
 * Exists to make retry logic explicit and readable.
 */
async function retryStep(step: PlanStep): Promise<unknown> {
  return await executeSingleStep(step);
}

// -------------------------------------------------------------
//  LLM AUTOFIX — REWRITE SINGLE STEP
// -------------------------------------------------------------
/**
 * Uses the LLM to rewrite a failing step.
 *
 * Inputs:
 *   • step  — the original failing step
 *   • error — the error thrown during execution
 *
 * LLM Responsibilities:
 *   • Return a corrected JSON version of the step
 *   • Preserve the step number
 *   • Preserve the tool unless clearly incorrect
 *   • Ensure all required fields for the tool are present
 *   • Output ONLY valid JSON (no commentary)
 *
 * This function is the core of the autofix mechanism.
 */
async function rewriteStep(step: PlanStep, error: unknown): Promise<PlanStep> {
  const completion = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `
${vectorSystemPrompt}

You are fixing a failing plan step for an autonomous agent.

Available tools:
${Object.keys(toolRegistry).join(", ")}

Tool schemas:
${JSON.stringify(toolRegistry, null, 2)}

Your job:
- Return a corrected version of the step as valid JSON.
- Keep the same "number" and "tool" unless the tool is clearly wrong.
- Ensure all required fields for that tool are present.
- Do NOT include commentary, only JSON.
        `
      },
      {
        role: "user",
        content: `
Original step:
${JSON.stringify(step, null, 2)}

Error:
${JSON.stringify(error, null, 2)}
        `
      }
    ]
  });

  const fixedJson = completion.choices[0].message.content ?? "";
  return JSON.parse(fixedJson);
}

// -------------------------------------------------------------
//  STEP VALIDATION
// -------------------------------------------------------------
//  Ensures a single step is structurally valid before execution.
//  Checks:
//    • Tool exists in the registry
//    • All required fields for that tool are present
// -------------------------------------------------------------
function validateStep(step: PlanStep): StepValidationResult {
  const entry = toolRegistry[step.tool];

  if (!entry) {
    return {
      valid: false,
      error: `Unknown tool "${step.tool}". Valid tools: ${Object.keys(toolRegistry).join(", ")}`
    };
  }

  for (const field of entry.requiredFields || []) {
    if ((step as any)[field] === undefined || (step as any)[field] === null) {
      return {
        valid: false,
        error: `Missing required field "${field}" for tool "${step.tool}".`
      };
    }
  }

  return { valid: true };
}

// -------------------------------------------------------------
//  PLAN VALIDATION
// -------------------------------------------------------------
//  Validates the entire plan before execution.
//  Ensures:
//    • Steps exist
//    • Each step passes validateStep()
//    • No structural issues before optimization or execution
// -------------------------------------------------------------
function validatePlan(plan: Plan): PlanValidationResult {
  const errors: string[] = [];

  if (!plan.steps || !Array.isArray(plan.steps) || plan.steps.length === 0) {
    errors.push("Plan must contain at least one step.");
    return { valid: false, errors };
  }

  const seenNumbers = new Set<number>();

  for (const step of plan.steps) {
    if (step.number === undefined || step.number === null) {
      errors.push("A step is missing its 'number' field.");
      continue;
    }

    if (seenNumbers.has(step.number)) {
      errors.push(`Duplicate step number detected: ${step.number}`);
    }
    seenNumbers.add(step.number);

    if (!step.tool) {
      errors.push(`Step ${step.number} is missing a 'tool' field.`);
      continue;
    }

    if (!toolRegistry[step.tool]) {
      errors.push(`Step ${step.number} uses unknown tool "${step.tool}".`);
      continue;
    }

    const required = toolRegistry[step.tool].requiredFields || [];
    for (const field of required) {
      if ((step as any)[field] === undefined || (step as any)[field] === null) {
        errors.push(
          `Step ${step.number} is missing required field "${field}" for tool "${step.tool}".`
        );
      }
    }
  }

  return {
    valid: errors.length === 0,
    errors
  };
}

// REWRITE ENTIRE PLAN (LLM AUTOFIX)
async function rewritePlan(plan: Plan, errors: unknown): Promise<Plan> {
  const completion = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `
${vectorSystemPrompt}

You are repairing an invalid plan for an autonomous agent.

Available tools:
${Object.keys(toolRegistry).join(", ")}

Tool schemas:
${JSON.stringify(toolRegistry, null, 2)}

Your job:
- Return a corrected version of the ENTIRE plan as valid JSON.
- Keep the same overall goal and step order unless the structure is clearly wrong.
- Ensure every step uses a valid tool.
- Ensure every step includes all required fields for that tool.
- Do NOT include commentary, only JSON.
        `
      },
      {
        role: "user",
        content: `
Original plan:
${JSON.stringify(plan, null, 2)}

Validation errors:
${JSON.stringify(errors, null, 2)}
        `
      }
    ]
  });

  const fixedJson = completion.choices[0].message.content ?? "";
  return JSON.parse(fixedJson);
}

// REWRITE REMAINING STEPS (MULTI-STEP AUTOFIX)
async function rewriteRemainingPlan(
  plan: Plan,
  failingStepIndex: number,
  error: unknown
): Promise<Plan> {
  const remainingSteps = plan.steps.slice(failingStepIndex);

  const completion = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `
${vectorSystemPrompt}

You are repairing the REMAINING STEPS of a failing plan for an autonomous agent.

Available tools:
${Object.keys(toolRegistry).join(", ")}

Tool schemas:
${JSON.stringify(toolRegistry, null, 2)}

Your job:
- Only rewrite the remaining steps, not the ones already completed.
- Keep the same overall goal.
- Ensure every step uses a valid tool.
- Ensure every step includes all required fields for that tool.
- Do NOT include commentary, only JSON array of steps.
        `
      },
      {
        role: "user",
        content: `
Original plan:
${JSON.stringify(plan, null, 2)}

Failing from step index: ${failingStepIndex}

Remaining steps:
${JSON.stringify(remainingSteps, null, 2)}

Error that triggered repair:
${JSON.stringify(error, null, 2)}
        `
      }
    ]
  });

    const fixedJson = completion.choices[0].message.content ?? "";
    const fixedSteps: PlanStep[] = JSON.parse(fixedJson);

  return {
    ...plan,
    steps: [
      ...plan.steps.slice(0, failingStepIndex),
      ...fixedSteps
    ]
  };
}

// =============================================================
//  DAG + OPTIMIZATION SUBSYSTEM
// =============================================================
//  Converts a linear plan into a dependency-aware execution graph.
//  Responsibilities:
//    • Detect dependencies between steps
//    • Build a DAG (Directed Acyclic Graph)
//    • Detect and extract cycles
//    • Perform topological sorting
//    • Compute parallel execution layers
//    • Optimize redundant or no-op steps
//
//  This subsystem ensures the plan is safe, minimal, and parallelizable.

// DAG + DEPENDENCY GRAPH
function buildDAG(steps: PlanStep[], deps: Map<number, Set<number>>): DAG {
  const adjacencyList = new Map<number, number[]>();
  const reverseAdjacencyList = new Map<number, number[]>();
  const inDegree = new Map<number, number>();

  for (let i = 0; i < steps.length; i++) {
    adjacencyList.set(i, []);
    reverseAdjacencyList.set(i, []);
    inDegree.set(i, 0);
  }

  for (let i = 0; i < steps.length; i++) {
    const dependencies = deps.get(i) || new Set<number>();

    for (const dep of dependencies) {
      adjacencyList.get(dep)!.push(i);
      reverseAdjacencyList.get(i)!.push(dep);
      inDegree.set(i, inDegree.get(i)! + 1);
    }
  }

  return { adjacencyList, reverseAdjacencyList, inDegree };
}

// TOPOLOGICAL SORT
function topologicalSort(dag: DAG): number[] {
  const { adjacencyList, inDegree } = dag;

  const queue: number[] = [];
  const result: number[] = [];

  for (const [node, degree] of inDegree.entries()) {
    if (degree === 0) queue.push(node);
  }

  while (queue.length > 0) {
    const current = queue.shift()!;
    result.push(current);

    for (const neighbor of adjacencyList.get(current)!) {
      inDegree.set(neighbor, inDegree.get(neighbor)! - 1);

      if (inDegree.get(neighbor) === 0) {
        queue.push(neighbor);
      }
    }
  }

  if (result.length !== adjacencyList.size) {
    throw new Error("Cycle detected in plan — cannot topologically sort.");
  }

  return result;
}

// PARALLEL LAYER COMPUTATION
function computeParallelLayers(dag: DAG): number[][] {
  const { adjacencyList, inDegree } = dag;

  const degree = new Map(inDegree);
  const layers: number[][] = [];
  let currentLayer: number[] = [];

  for (const [node, deg] of degree.entries()) {
    if (deg === 0) currentLayer.push(node);
  }

  while (currentLayer.length > 0) {
    layers.push(currentLayer);

    const nextLayer: number[] = [];

    for (const node of currentLayer) {
      for (const neighbor of adjacencyList.get(node)!) {
        degree.set(neighbor, degree.get(neighbor)! - 1);

        if (degree.get(neighbor) === 0) {
          nextLayer.push(neighbor);
        }
      }
    }

    currentLayer = nextLayer;
  }

  const totalNodes = adjacencyList.size;
  const counted = layers.reduce((sum, layer) => sum + layer.length, 0);

  if (counted !== totalNodes) {
    throw new Error("Cycle detected while computing parallel layers.");
  }

  return layers;
}

// CYCLE DETECTION
function detectCycle(dag: DAG): boolean {
  const { adjacencyList, inDegree } = dag;

  const degree = new Map(inDegree);
  const queue: number[] = [];

  for (const [node, deg] of degree.entries()) {
    if (deg === 0) queue.push(node);
  }

  let visitedCount = 0;

  while (queue.length > 0) {
    const current = queue.shift()!;
    visitedCount++;

    for (const neighbor of adjacencyList.get(current)!) {
      degree.set(neighbor, degree.get(neighbor)! - 1);
      if (degree.get(neighbor) === 0) queue.push(neighbor);
    }
  }

  return visitedCount !== adjacencyList.size;
}

// CYCLE EXTRACTION
function extractCycle(dag: DAG): number[] | null {
  const { adjacencyList } = dag;

  const visited = new Set<number>();
  const stack = new Set<number>();
  const parent = new Map<number, number>();

  function dfs(node: number): number[] | null {
    visited.add(node);
    stack.add(node);

    for (const neighbor of adjacencyList.get(node)!) {
      if (!visited.has(neighbor)) {
        parent.set(neighbor, node);
        const cycle = dfs(neighbor);
        if (cycle) return cycle;
      } else if (stack.has(neighbor)) {
        const cycle = [neighbor];
        let cur = node;
        while (cur !== neighbor) {
          cycle.push(cur);
          cur = parent.get(cur)!;
        }
        cycle.reverse();
        return cycle;
      }
    }

    stack.delete(node);
    return null;
  }

  for (const node of adjacencyList.keys()) {
    if (!visited.has(node)) {
      const cycle = dfs(node);
      if (cycle) return cycle;
    }
  }

  return null;
}

// DETERMINISTIC MERGE OF FILE WRITES
function deterministicOptimizeSteps(steps: PlanStep[]): PlanStep[] {
  const optimized: PlanStep[] = [];
  const pendingWrites = new Map<string, { index: number; step: PlanStep }>();

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];

    if (step.tool === "fileWriterTool" && step.filename) {
      const key = step.filename;

      if (!pendingWrites.has(key)) {
        const clone = { ...step };
        pendingWrites.set(key, { index: optimized.length, step: clone });
        optimized.push(clone);
      } else {
        const existing = pendingWrites.get(key)!;
        const merged: PlanStep = {
          ...existing.step,
          content: (existing.step.content || "") + (step.content || ""),
          description: existing.step.description || step.description
        };

        optimized[existing.index] = merged;
        pendingWrites.set(key, { index: existing.index, step: merged });
      }
    } else {
      optimized.push({ ...step });
    }
  }

  return optimized;
}

// REMOVE NO-OP STEPS
function removeNoOpSteps(steps: PlanStep[]): PlanStep[] {
  return steps.filter(step => {
    if (!step.tool) return false;

    if (step.tool === "fileWriterTool") {
      if (!step.filename) return false;
      if (step.content === "" || step.content === null || step.content === undefined) {
        return false;
      }
    }

    const meaningfulFields = Object.keys(step).filter(k =>
      !["number", "description", "autofix"].includes(k)
    );

    return meaningfulFields.length > 0;
  });
}

// DEPENDENCY DETECTION
function detectDependencies(steps: PlanStep[]): Map<number, Set<number>> {
  const deps = new Map<number, Set<number>>();

  for (let i = 0; i < steps.length; i++) {
    deps.set(i, new Set<number>());
  }

  // Simple heuristic:
  // - fileReaderTool depends on previous fileWriterTool for same filename
  // - fileUpdaterTool depends on previous fileWriterTool for same filename
  // - fileWriterTool depends on previous fileWriterTool for same filename
  const lastWrite = new Map<string, number>();

  for (let i = 0; i < steps.length; i++) {
    const step = steps[i];

    if (step.tool === "fileWriterTool" && step.filename) {
      if (lastWrite.has(step.filename)) {
        deps.get(i)!.add(lastWrite.get(step.filename)!);
      }
      lastWrite.set(step.filename, i);
    }

    if (step.tool === "fileReaderTool" && step.filename) {
      if (lastWrite.has(step.filename)) {
        deps.get(i)!.add(lastWrite.get(step.filename)!);
      }
    }

    if (step.tool === "fileUpdaterTool" && step.filename) {
      if (lastWrite.has(step.filename)) {
        deps.get(i)!.add(lastWrite.get(step.filename)!);
      }
      lastWrite.set(step.filename, i);
    }
  }

  return deps;
}

// PLAN OPTIMIZATION PIPELINE
async function optimizePlan(plan: Plan): Promise<Plan> {
  function stripCodeFences(text: string): string {
    return text
      .replace(/```json/gi, "")
      .replace(/```/g, "")
      .trim();
  }

  // --- 1. LLM-POWERED OPTIMIZATION ---
  const completion = await client.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [
      {
        role: "system",
        content: `
${vectorSystemPrompt}

You are optimizing a plan for an autonomous agent.

Your job:
- Improve efficiency.
- Merge redundant steps.
- Reorder steps logically.
- Remove unnecessary steps.
- Keep the same goal.
- Ensure all required fields for each tool remain valid.
- Return ONLY the optimized steps as JSON array.
        `
      },
      {
        role: "user",
        content: `
Original steps:
${JSON.stringify(plan.steps, null, 2)}
        `
      }
    ]
  });

let optimizedJson = completion.choices[0].message.content ?? "";
optimizedJson = stripCodeFences(optimizedJson);

  let llmOptimizedSteps: PlanStep[] = JSON.parse(optimizedJson);

  // --- 2. REMOVE NO-OPS ---
  llmOptimizedSteps = removeNoOpSteps(llmOptimizedSteps);

  // --- 3. MERGE REDUNDANT FILE WRITES ---
  let optimizedSteps = deterministicOptimizeSteps(llmOptimizedSteps);

  // --- 4. REMOVE EXACT DUPLICATES ---
  optimizedSteps = optimizedSteps.filter((step, index, arr) => {
    return index === arr.findIndex(s => JSON.stringify(s) === JSON.stringify(step));
  });

  // --- 5. MERGE CONSECUTIVE WRITES TO SAME FILE ---
  for (let i = 0; i < optimizedSteps.length - 1; i++) {
    const current = optimizedSteps[i];
    const next = optimizedSteps[i + 1];

    if (
      current.tool === "fileWriterTool" &&
      next.tool === "fileWriterTool" &&
      current.filename === next.filename
    ) {
      current.content = (current.content || "") + "\n" + (next.content || "");
      optimizedSteps.splice(i + 1, 1);
      i--;
    }
  }

  // --- 6. DEPENDENCY DETECTION ---
  const deps = detectDependencies(optimizedSteps);

  // --- 7. BUILD DAG ---
  const dag = buildDAG(optimizedSteps, deps);

  // --- 8. CYCLE DETECTION ---
  if (detectCycle(dag)) {
    const cycleNodes = extractCycle(dag);
    const cycleSteps = cycleNodes?.map(i => optimizedSteps[i]) || [];

    console.log("CYCLE DETECTED:");
    console.dir(cycleSteps, { depth: null });

    if (!plan.autofix) {
      throw new Error("Cycle detected in plan. Enable autofix to repair.");
    }

    const fixedPlan = await rewritePlan(plan, {
      type: "cycle",
      cycle: cycleSteps.map(s => ({
        number: s.number,
        description: s.description,
        tool: s.tool
      }))
    });

    const recheck = validatePlan(fixedPlan);
    if (!recheck.valid) {
      throw new Error("Cycle autofix failed — produced invalid plan.");
    }

    return await optimizePlan(fixedPlan);
  }

  // --- 9. TOPOLOGICAL SORT ---
  const topoOrder = topologicalSort(dag);
  optimizedSteps = topoOrder.map(i => optimizedSteps[i]);

  // --- 10. PARALLEL LAYERS ---
  const layers = computeParallelLayers(dag);

  optimizedSteps = optimizedSteps.map((step, idx) => {
    const layerIndex = layers.findIndex(layer => layer.includes(idx));
    return {
      ...step,
      parallelGroup: layerIndex + 1
    };
  });

  // --- 11. RENUMBER STEPS ---
  optimizedSteps = optimizedSteps.map((step, index) => ({
    ...step,
    number: index + 1
  }));

  return {
    ...plan,
    steps: optimizedSteps
  };
}

// =============================================================
//  EXECUTION ENGINE
// =============================================================
//  Executes the optimized plan using a hybrid model:
//    • Parallel execution for independent steps
//    • Sequential fallback for dependent steps
//    • Automatic retry with LLM-powered autofix on failure
//
//  The exported function `executePlan()` is the main entry point.
// =============================================================

// PARALLEL EXECUTION ENGINE
async function executeParallelGroups(plan: Plan): Promise<StepExecutionResult[]> {
  const results: StepExecutionResult[] = [];

  const groups = new Map<number, PlanStep[]>();
  for (const step of plan.steps) {
    const group = step.parallelGroup ?? 1;
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group)!.push(step);
  }

  const sortedGroups = Array.from(groups.keys()).sort((a, b) => a - b);

  for (const group of sortedGroups) {
    const stepsInGroup = groups.get(group)!;

    const groupResults = await Promise.all(
      stepsInGroup.map(async (step): Promise<StepExecutionResult> => {
        let output: unknown = null;
        let error: unknown = null;
        let fixedStep: PlanStep | null = null;
        let autofixAttempted = false;

        // STEP-LEVEL VALIDATION
        const validation = validateStep(step);
        if (!validation.valid) {
          error = {
            message: validation.error,
            step: step.number,
            description: step.description
          };

          if (step.autofix) {
            try {
              autofixAttempted = true;
              fixedStep = await rewriteStep(step, error);
              const retryOutput = await executeSingleStep(fixedStep);

              if ((retryOutput as any)?.success === false) {
                throw new Error((retryOutput as any).error || "Unknown tool error");
              }

              output = retryOutput;
              error = null;

            } catch (fixErr: any) {
              error = {
                message: fixErr.message,
                step: step.number,
                autofixFailed: true
              };
            }
          }

          return {
            step: step.number,
            description: step.description ?? null,
            tool: step.tool,
            parallelGroup: step.parallelGroup ?? null,
            startTime: null,
            endTime: null,
            durationMs: null,
            output,
            error,
            autofixAttempted,
            fixedStep
          };
        }

        // NORMAL EXECUTION
        try {
          const startTime = Date.now();
          output = await executeSingleStep(step);
          const endTime = Date.now();
          const durationMs = endTime - startTime;

          if ((output as any)?.success === false) {
            throw new Error((output as any).error || "Unknown tool error");
          }

          return {
            step: step.number,
            description: step.description ?? null,
            tool: step.tool,
            parallelGroup: step.parallelGroup ?? null,
            startTime,
            endTime,
            durationMs,
            output,
            error: null,
            autofixAttempted,
            fixedStep
          };

        } catch (err: any) {
          error = {
            message: err.message,
            step: step.number,
            description: step.description
          };

          // RETRY LOGIC
          if (step.retry && step.retry > 0) {
            try {
              const startTime = Date.now();
              output = await retryStep(step);
              const endTime = Date.now();
              const durationMs = endTime - startTime;

              if ((output as any)?.success === false) {
                throw new Error((output as any).error || "Unknown tool error");
              }

              return {
                step: step.number,
                description: step.description ?? null,
                tool: step.tool,
                parallelGroup: step.parallelGroup ?? null,
                startTime,
                endTime,
                durationMs,
                output,
                error: null,
                autofixAttempted,
                fixedStep
              };

            } catch (retryErr: any) {
              error = {
                message: retryErr.message,
                step: step.number,
                retryFailed: true
              };
            }
          }

          // STEP-LEVEL AUTOFIX
          if (error && step.autofix) {
            try {
              autofixAttempted = true;

              const startTime = Date.now();
              fixedStep = await rewriteStep(step, error);
              const retryOutput = await executeSingleStep(fixedStep);
              const endTime = Date.now();
              const durationMs = endTime - startTime;

              if ((retryOutput as any)?.success === false) {
                throw new Error((retryOutput as any).error || "Unknown tool error");
              }

              return {
                step: step.number,
                description: step.description ?? null,
                tool: step.tool,
                parallelGroup: step.parallelGroup ?? null,
                startTime,
                endTime,
                durationMs,
                output: retryOutput,
                error: null,
                autofixAttempted,
                fixedStep
              };

            } catch (fixErr: any) {
              error = {
                message: fixErr.message,
                step: step.number,
                autofixFailed: true
              };
            }
          }

          // FINAL FAILURE RETURN
          return {
            step: step.number,
            description: step.description ?? null,
            tool: step.tool,
            parallelGroup: step.parallelGroup ?? null,
            startTime: null,
            endTime: null,
            durationMs: null,
            output,
            error,
            autofixAttempted,
            fixedStep
          };
        }
      })
    );

    results.push(...groupResults);
  }

  return results;
}

// SEQUENTIAL EXECUTION ENGINE
export async function executePlan(plan: Plan): Promise<StepExecutionResult[]> {
  const results: StepExecutionResult[] = [];

  // PLAN-LEVEL VALIDATION
  const planValidation = validatePlan(plan);

  if (!planValidation.valid) {
    if (plan.autofix) {
      try {
        const fixedPlan = await rewritePlan(plan, planValidation.errors);
        const recheck = validatePlan(fixedPlan);

        if (!recheck.valid) {
          return [{
            step: null,
            description: "Plan autofix failed",
            tool: null,
            output: null,
            error: {
              message: "Plan autofix failed",
              details: recheck.errors
            },
            autofixAttempted: true,
            fixedStep: null,
            parallelGroup: null,
            startTime: null,
            endTime: null,
            durationMs: null
          }];
        }

        plan = fixedPlan;

      } catch (err: any) {
        return [{
          step: null,
          description: "Plan autofix crashed",
          tool: null,
          output: null,
          error: {
            message: err.message,
            details: planValidation.errors
          },
          autofixAttempted: true,
          fixedStep: null,
          parallelGroup: null,
          startTime: null,
          endTime: null,
          durationMs: null
        }];
      }

    } else {
      return [{
        step: null,
        description: "Plan validation failed",
        tool: null,
        output: null,
        error: {
          message: "Plan validation failed",
          details: planValidation.errors
        },
        autofixAttempted: false,
        fixedStep: null,
        parallelGroup: null,
        startTime: null,
        endTime: null,
        durationMs: null
      }];
    }
  }

  // PLAN OPTIMIZATION
  if (plan.optimize) {
    try {
      const optimized = await optimizePlan(plan);
      const recheck = validatePlan(optimized);

      if (!recheck.valid) {
        throw new Error("Optimized plan is invalid");
      }

      plan = optimized;

      console.log("FINAL OPTIMIZED STEPS BEFORE EXECUTION:");
      console.dir(plan.steps, { depth: null });

    } catch (optErr: any) {
      results.push({
        step: null,
        description: "Plan optimization failed",
        tool: null,
        output: null,
        error: { message: optErr.message },
        autofixAttempted: false,
        fixedStep: null,
        parallelGroup: null,
        startTime: null,
        endTime: null,
        durationMs: null
      });
    }
  }

  // PARALLEL EXECUTION MODE
  if (plan.parallel) {
    const parallelResults = await executeParallelGroups(plan);
    results.push(...parallelResults);

    console.log("\n=== EXECUTION TIMELINE ===");
    for (const r of parallelResults) {
      const duration = r.durationMs !== null ? `${r.durationMs}ms` : "N/A";
      const group = r.parallelGroup ?? 1;
      console.log(`Step #${r.step}  [Group ${group}]  ${r.description}  —  ${duration}`);
    }
    console.log("=== END TIMELINE ===\n");

    return results;
  }

  // SEQUENTIAL EXECUTION
  for (let i = 0; i < plan.steps.length; i++) {
    const step = plan.steps[i];

    let output: unknown = null;
    let error: unknown = null;
    let fixedStep: PlanStep | null = null;
    let autofixAttempted = false;

    // STEP VALIDATION
    const validation = validateStep(step);

    if (!validation.valid) {
      error = {
        message: validation.error,
        step: step.number,
        description: step.description
      };

      if (step.autofix) {
        try {
          autofixAttempted = true;
          fixedStep = await rewriteStep(step, error);
          const retryOutput = await executeSingleStep(fixedStep);

          if ((retryOutput as any)?.success === false) {
            throw new Error((retryOutput as any).error || "Unknown tool error");
          }

          output = retryOutput;
          error = null;

        } catch (fixErr: any) {
          error = {
            message: fixErr.message,
            step: step.number,
            autofixFailed: true
          };
        }
      }

      results.push({
        step: step.number,
        description: step.description ?? null,
        tool: step.tool,
        output,
        error,
        autofixAttempted,
        fixedStep,
        parallelGroup: step.parallelGroup ?? null,
        startTime: null,
        endTime: null,
        durationMs: null
      });

      continue;
    }

    // NORMAL EXECUTION
    try {
      output = await executeSingleStep(step);

      if ((output as any)?.success === false) {
        throw new Error((output as any).error || "Unknown tool error");
      }

    } catch (err: any) {
      error = {
        message: err.message,
        step: step.number,
        description: step.description
      };

      // RETRY LOGIC
      if (step.retry && step.retry > 0) {
        try {
          output = await retryStep(step);

          if ((output as any)?.success === false) {
            throw new Error((output as any).error || "Unknown tool error");
          }

          error = null;

        } catch (retryErr: any) {
          error = {
            message: retryErr.message,
            step: step.number,
            retryFailed: true
          };
        }
      }

      // STEP-LEVEL AUTOFIX
      if (error && step.autofix) {
        try {
          autofixAttempted = true;

          fixedStep = await rewriteStep(step, error);
          const retryOutput = await executeSingleStep(fixedStep);

          if ((retryOutput as any)?.success === false) {
            throw new Error((retryOutput as any).error || "Unknown tool error");
          }

          output = retryOutput;
          error = null;

        } catch (fixErr: any) {
          error = {
            message: fixErr.message,
            step: step.number,
            autofixFailed: true
          };
        }
      }

      // MULTI-STEP AUTOFIX
      if (error && plan.autofix) {
        try {
          autofixAttempted = true;

          const currentIndex = i;
          const fixedPlan = await rewriteRemainingPlan(plan, currentIndex, error);

          const recheck = validatePlan(fixedPlan);
          if (!recheck.valid) {
            throw new Error("Multi-step autofix produced an invalid plan");
          }

          plan = fixedPlan;

          const updatedStep = plan.steps[currentIndex];
          const retryOutput = await executeSingleStep(updatedStep);

          if ((retryOutput as any)?.success === false) {
            throw new Error((retryOutput as any).error || "Unknown tool error");
          }

          output = retryOutput;
          error = null;

        } catch (multiErr: any) {
          error = {
            message: multiErr.message,
            step: step.number,
            multiStepAutofixFailed: true
          };
        }
      }
    }

    results.push({
      step: step.number,
      description: step.description ?? null,
      tool: step.tool,
      output,
      error,
      autofixAttempted,
      fixedStep,
      parallelGroup: step.parallelGroup ?? null,
      startTime: null,
      endTime: null,
      durationMs: null
    });
  }

  return results;
}
